//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ChuDe
    {
       
        [Display(Name = "Category ID")]
        public int MaChuDe { get; set; }
        [Required(ErrorMessage = "{0} Can't be left blank")]
        [Display(Name = "Category Name")]
        public string TenChuDe { get; set; }
    }
}
