//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class NhaXuatBan
    {
       
        [Display(Name = "Publisher ID")]
        public int MaNXB { get; set; }
        [Required(ErrorMessage = "{0} Can't be left blank")]
        [Display(Name = "Publisher Name")]
        public string TenNXB { get; set; }
        [Required(ErrorMessage = "{0} Can't be left blank")]
        [Display(Name = "Address")]
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "{0} Can't be left blank")]
        [Display(Name = "Fone")]
        public string DienThoai { get; set; }
    }
}
